### ISSUE TITLE
AWS Elastic Beanstalk Build Error: node-gyp requires that the user home directory is specified in either of the environmental variables HOME or USERPROFILE

### ISSUE THREAD

**Issue by deerawan** [nodejs/node-gyp#414]
I have aws elastic beanstalk for node js application and I uploaded my node js app (zip file) to my instance but I saw this error in aws logs

The Error

```
node-gyp requires that the 'user'\''s' home directory is specified in either of the environmental variables HOME or 'USERPROFILE\n' at new Gyp '(/opt/elasticbeanstalk/node-install/node-v0.8.26-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54:11
```

Package.json

```
{
  "name": "testing-beanstalk",
  "description": "Testing Beanstalk",
  "author": "Bugan",
  "version": "1.0",
  "private": true,  
  "dependencies": {
    "express": "3.x",
    "socket.io": "0.9.6",
    "mysql": "2.0.1",
    "cron": "1.0.0",
  }
}
```

Any idea to solve this problem? How to set user home directory? 

Thank you before

**Comment by ajf** [comment]
@eric-tucker :+1:

**Comment by smoya** [comment]
What is the current status of this issue? Because i have the same problem.

**Comment by kylev** [comment]
FWIW, I deployed a Node app to EB based on Amazon Linux 2015.03 today and this problem is no longer present. I poked around a bit and `/opt/elasticbeanstalk/containerfiles/ebnode.py` (which is used to drive the npm install) now sets `$HOME`.

(I'm not a fan of build tools depending on a homedir, but it does now seem to work.)

**Comment by chadkouse** [comment]
good news. Maybe I will try eb again. I gave up after many, many confusing
and stalled deployments.

On Thu, Jul 23, 2015, 5:46 PM Kyle VanderBeek <notifications@github.com>
wrote:

> FWIW, I deployed a Node app to EB based on Amazon Linux 2015.03 today and
> this problem is no longer present. I poked around a bit and
> /opt/elasticbeanstalk/containerfiles/ebnode.py (which is used to drive
> the npm install) now sets $HOME.
>
> (I'm not a fan of build tools depending on a homedir, but it does now seem
> to work.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TooTallNate/node-gyp/issues/414#issuecomment-124248111>
> .
>
-- 

--chad

**Comment by rhyeal** [comment]
We ended up using a slightly modified version for our problem. Leaving it here for anyone else who may need it (bcrypt specific):

```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh" :
    mode: "000775"
    owner: root
    group: root
    content: |
      #!/bin/bash
      #==============================================================================
      # Copyright 2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.
      #
      # Licensed under the Amazon Software License (the "License"). You may not use
      # this file except in compliance with the License. A copy of the License is
      # located at
      #
      #       http://aws.amazon.com/asl/
      #
      # or in the "license" file accompanying this file. This file is distributed on
      # an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
      # implied. See the License for the specific language governing permissions
      # and limitations under the License.
      #==============================================================================

      export HOME=/home/ec2-user
      export USERPROFILE=/home/ec2-user

      sudo rm -rf /tmp/deployment/application/node_modules/bcrypt

      set -xe

      /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install


```
